fix: sub-command region conflict with options_define region
```
$ rm -rf /root/.tccli/default.configure
$ tccli --version
3.0.924.1
$ tccli region  DescribeRegions  --Product cvm
usage: tccli [options] <command> <subcommand> [<subcommand> ...] [parameters]
To tccli help text, you can run:

  tccli help
  tccli configure help
  tccli service[cvm] help
  tccli service[cvm] action[RunInstances] help

config file:/root/.tccli/default.configure error, string indices must be integers

$ cat /root/.tccli/log/tccli.log
... ...
[2023-08-01 11:06:36,780] [4874] [tccli.main] [INFO] tccli region DescribeRegions --Product cvm
[2023-08-01 11:06:36,893] [4874] [tccli.main] [ERROR] config file:/root/.tccli/default.configure error, string indices must be integers
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/tccli/services/region/region_client.py", line 265, in parse_global_arg
    version = conf["region"][OptionsDefine.Version]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/tccli/main.py", line 41, in main
    CLICommand()()
  File "/root/venv/lib/python3.6/site-packages/tccli/command.py", line 49, in __call__
    return command_map[parsed_args.command](remaining, parsed_args)
  File "/root/venv/lib/python3.6/site-packages/tccli/command.py", line 189, in __call__
    return command_map[parsed_args.operation](remaining, parsed_globals)
  File "/root/venv/lib/python3.6/site-packages/tccli/command.py", line 286, in __call__
    return self._action_caller(action_parameters, vars(parsed_globals))
  File "/root/venv/lib/python3.6/site-packages/tccli/services/region/region_client.py", line 73, in doDescribeRegions
    g_param = parse_global_arg(parsed_globals)
  File "/root/venv/lib/python3.6/site-packages/tccli/services/region/region_client.py", line 271, in parse_global_arg
    raise ConfigurationError("config file:%s error, %s" % (conf_path, str(err)))
tccli.exceptions.ConfigurationError: config file:/root/.tccli/default.configure error, string indices must be integers
```

```
$ rm -rf /root/.tccli/default.configure
$ tccli --version
3.0.924.1
$ grep "region" /root/.tccli/default.configure
  "region": "ap-guangzhou",
```

Signed-off-by: Chenyang Yan <memory.yancy@gmail.com>